version: "3.8"
services:
  back:
    image: matthieuskr/bobapp-back:latest
    container_name: bobapp-back
    expose:
      - "8080"
    networks:
      - mynetworks

  front:
    image: matthieuskr/bobapp-front:latest
    container_name: bobapp-front
    depends_on:
      - back
    ports:
      - "4200:80"
    networks:
      - mynetworks

networks:
  mynetworks:
    driver: bridge
