services:
  back:
    image: matthieuskr/bobapp-back:latest
    container_name: bobapp-back
    ports:
      - "8080:8080"

  front:
    image: matthieuskr/bobapp-front:latest
    container_name: bobapp-front
    ports:
      - "80:80"
    depends_on:
      - back
