version: '3'
services:
  back:
    image: matthieuskr/bobapp-back
    container_name: bobapp-back
    ports:
      - "8080:8080"

  front:
    image: matthieuskr/bobapp-front
    container_name: bobapp-front
    ports:
      - "4200:80"
    depends_on:
      - back
