on:
  workflow_call:


name: Test BackEnd CI/CD
run-name: Test Backend - "${{ github.event.head_commit.message }} - ${{ github.actor }}"

jobs:
  run-tests:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: back
      steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Run tests with Maven
        run: mvn clean test

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco