on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

name: Sonar FrontEnd CI/CD
run-name: Sonar Frontend - "${{ github.event.head_commit.message }} - ${{ github.actor }}"

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=matthieuskrzypczak_bobapp-front
            -Dsonar.organization=matthieuskrzypczak
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

