name: Test BackEnd CI/CD
run-name: ${{ github.actor }} 
on:
  push:
      branches:
         - main
  pull_request:
      branches:
         - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64

        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

     - name: Run tests with Maven
         run: mvn clean test

     - name: Generate JaCoCo report
        run: mvn jacoco:report

     - name: Upload JaCoCo coverage report
         uses: actions/upload-artifact@v3
         with:
           name: jacoco-report
           path: back/target/site/jacoco



       
      
