name: CI/CD Orchestration
run-name: CI/CD Orchestration - "${{ github.event.head_commit.message }} - ${{ github.actor }}"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backtest:
    uses: ./.github/workflows/back-tests.yml

  fronttest:
    uses: ./.github/workflows/front-tests.yml

  backsonar:
    needs: [backtest, fronttest]
    if: ${{ success() }}
    uses: ./.github/workflows/back-sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  frontsonar:
    needs: [backtest, fronttest]
    if: ${{ success() }}
    uses: ./.github/workflows/front-sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
